import type { NavItem, Product, Testimonial, FAQ, GalleryItem, Metric, BlogPost } from "@/types";

export const SITE_CONFIG = {
  name: "Canvasify",
  tagline: "Turn Memories Into Masterpieces",
  description:
    "Transform your precious memories into stunning personalized paint-by-number masterpieces using AI. Upload any photo and receive a custom art kit delivered to your door.",
  url: "https://canvasify.art",
  logo: "/logo.svg",
  email: "hello@canvasify.art",
  phone: "+91 98765 43210",
  social: {
    instagram: "https://instagram.com/canvasifyart",
    twitter: "https://twitter.com/canvasifyart",
    youtube: "https://youtube.com/@canvasifyart",
    pinterest: "https://pinterest.com/canvasifyart",
    facebook: "https://facebook.com/canvasifyart",
  },
};

export const NAV_ITEMS: NavItem[] = [
  { label: "Home", href: "/" },
  {
    label: "Products",
    href: "/products",
    children: [
      { label: "Digital Download", href: "/products/digital" },
      { label: "Canvas Kit", href: "/products/canvas-kit" },
      { label: "Framed Artwork", href: "/products/framed" },
      { label: "Creative Club", href: "/products/subscription", badge: "NEW" },
    ],
  },
  { label: "Gallery", href: "/gallery" },
  { label: "Pricing", href: "/pricing" },
  { label: "Blog", href: "/blog" },
  { label: "About", href: "/about" },
];

export const PRODUCTS: Product[] = [
  {
    id: "digital",
    name: "Digital Download",
    description: "Instant access to your personalized paint-by-number template as a high-resolution PDF.",
    price: 499,
    currency: "INR",
    type: "digital",
    features: [
      "High-res PDF template (A3 size)",
      "Color-coded number guide",
      "Digital palette reference",
      "Unlimited reprints",
      "Instant delivery",
      "Mobile-friendly preview",
    ],
    cta: "Get Digital",
  },
  {
    id: "canvas_kit",
    name: "Canvas Kit",
    description: "Complete paint-by-number kit with premium canvas, paints, and brushes delivered to your door.",
    price: 1499,
    currency: "INR",
    type: "canvas_kit",
    popular: true,
    features: [
      "Everything in Digital",
      "Premium 40x50cm canvas",
      "24 acrylic paint pots",
      "3 professional brushes",
      "Numbered paint guide",
      "Elegant gift box",
      "Free shipping",
    ],
    cta: "Get Canvas Kit",
  },
  {
    id: "framed",
    name: "Framed Artwork",
    description: "Your masterpiece professionally printed and framed — ready to hang and impress.",
    price: 3999,
    currency: "INR",
    type: "framed",
    features: [
      "Everything in Canvas Kit",
      "Professional printing",
      "Premium wooden frame",
      "UV-protective glass",
      "Wall mounting hardware",
      "Certificate of authenticity",
      "White glove delivery",
    ],
    cta: "Get Framed Art",
  },
];

export const SUBSCRIPTION = {
  id: "creative_club",
  name: "Creative Club",
  price: 299,
  currency: "INR",
  period: "month",
  description: "Unlimited creativity for art enthusiasts",
  features: [
    "1 free template per month",
    "50% off all Canvas Kits",
    "Early access to new features",
    "Exclusive monthly challenges",
    "Members-only gallery",
    "Priority customer support",
    "Free digital downloads",
    "Monthly art inspiration box",
  ],
};

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Priya Sharma",
    role: "Wedding Photographer",
    location: "Mumbai, India",
    avatar: "PS",
    rating: 5,
    text: "I ordered a paint-by-number kit of our wedding photo and it turned out absolutely stunning. The colors were perfectly matched and the detail was incredible. My husband and I painted it together on our anniversary — best gift ever!",
    project_type: "Wedding Photo",
    verified: true,
  },
  {
    id: "2",
    name: "Rajesh Kumar",
    role: "Software Engineer",
    location: "Bangalore, India",
    avatar: "RK",
    rating: 5,
    text: "Ordered this as a birthday gift for my mother — a portrait of our family dog who passed away. She cried happy tears when she saw it. The AI processing was shockingly accurate. Worth every rupee.",
    project_type: "Pet Portrait",
    verified: true,
  },
  {
    id: "3",
    name: "Ananya Patel",
    role: "Interior Designer",
    location: "Delhi, India",
    avatar: "AP",
    rating: 5,
    text: "As an interior designer, I recommend Canvasify to all my clients. The framed artwork option is exceptional — museum quality printing and the frame is gorgeous. My clients always ask where I got it.",
    project_type: "Home Portrait",
    verified: true,
  },
  {
    id: "4",
    name: "Vikram Mehta",
    role: "Entrepreneur",
    location: "Pune, India",
    avatar: "VM",
    rating: 5,
    text: "Used Canvasify for corporate gifting — ordered 50 personalized kits for our team. The B2B team was incredibly helpful, delivery was on time, and our employees absolutely loved them. Will definitely reorder.",
    project_type: "Corporate Gift",
    verified: true,
  },
  {
    id: "5",
    name: "Sneha Nair",
    role: "Teacher",
    location: "Chennai, India",
    avatar: "SN",
    rating: 5,
    text: "I use Canvasify in my art classes! The kids love working on their own personalized paintings. The educational kits are affordable and the digital templates are perfect for printing multiple copies.",
    project_type: "Educational",
    verified: true,
  },
  {
    id: "6",
    name: "Arjun Singh",
    role: "Travel Blogger",
    location: "Jaipur, India",
    avatar: "AS",
    rating: 5,
    text: "Turned my favorite travel photo from Santorini into a paint-by-number. It's now the centerpiece of my living room. The detail in the white buildings and blue domes is breathtaking. Pure art.",
    project_type: "Travel Memory",
    verified: true,
  },
  {
    id: "7",
    name: "Meera Iyer",
    role: "Homemaker",
    location: "Hyderabad, India",
    avatar: "MI",
    rating: 5,
    text: "I'm not an artist at all, but the paint-by-number system made me feel like one! Completed my first painting in a week and I'm so proud of it. The instructions were clear and the paints were beautiful.",
    project_type: "Family Portrait",
    verified: true,
  },
  {
    id: "8",
    name: "Amit Desai",
    role: "Architect",
    location: "Ahmedabad, India",
    avatar: "AD",
    rating: 5,
    text: "Ordered a paint kit of my dream home I designed for a client. They loved it as a housewarming gift so much that they've ordered three more for friends. Canvasify's quality is unmatched.",
    project_type: "Architecture",
    verified: true,
  },
];

export const FAQS: FAQ[] = [
  {
    id: "1",
    category: "Getting Started",
    question: "How does the AI transformation work?",
    answer: "Our advanced AI analyzes your photo using computer vision to identify regions, objects, and color areas. It then intelligently simplifies the image into distinct numbered sections with an optimized color palette — making it perfect for paint-by-number. The whole process takes under 5 minutes.",
  },
  {
    id: "2",
    category: "Getting Started",
    question: "What types of photos work best?",
    answer: "High-resolution photos with clear subjects work best. Great choices include portraits, pet photos, landscapes, wedding photos, and architectural shots. We recommend at least 2MP resolution. Avoid heavily blurred, very dark, or extremely low-contrast images.",
  },
  {
    id: "3",
    category: "Products",
    question: "What's included in the Canvas Kit?",
    answer: "Every Canvas Kit includes a premium pre-printed 40x50cm canvas with numbered regions, 24 carefully matched acrylic paint pots, 3 professional brushes (fine, medium, flat), a full-color paint reference guide, and an elegant gift-ready box. All materials are non-toxic and archival quality.",
  },
  {
    id: "4",
    category: "Products",
    question: "How large is the canvas?",
    answer: "Our standard canvas is 40x50cm (approximately 16x20 inches). For custom sizes or larger formats, contact our team. We offer sizes up to 60x80cm for an additional fee.",
  },
  {
    id: "5",
    category: "Orders",
    question: "How long does delivery take?",
    answer: "Digital downloads are instant. Canvas Kits are produced within 2-3 business days and delivered within 5-7 business days across India. Framed Artwork takes 5-7 business days to produce and 7-10 for delivery. We ship pan-India with tracking.",
  },
  {
    id: "6",
    category: "Orders",
    question: "Do you offer international shipping?",
    answer: "Yes! We ship to 40+ countries. International delivery typically takes 10-15 business days. Shipping rates vary by destination and are calculated at checkout.",
  },
  {
    id: "7",
    category: "Quality",
    question: "What quality are the paints?",
    answer: "We use premium acrylic paints that are vibrant, non-toxic, and archival-quality. Once dry, they're water-resistant. Our paints are specifically formulated for canvas and won't crack or fade over time.",
  },
  {
    id: "8",
    category: "Quality",
    question: "Will my painting look exactly like the photo?",
    answer: "The finished painting will be an artistic interpretation of your photo — that's the beauty of it! The AI optimizes the image to create the best painting experience while preserving the essence and emotion of the original. Most customers are amazed at how close it is.",
  },
  {
    id: "9",
    category: "Customization",
    question: "Can I choose the number of colors?",
    answer: "Yes! You can choose between 12, 24, or 36 color palettes. Fewer colors make painting easier and faster (great for beginners); more colors create more realistic, detailed results (recommended for experienced painters).",
  },
  {
    id: "10",
    category: "Customization",
    question: "Can I crop or adjust my photo before processing?",
    answer: "Absolutely. After uploading, you can crop, rotate, adjust brightness/contrast, and choose which area to focus on. Our editor lets you fine-tune before AI processing begins.",
  },
  {
    id: "11",
    category: "Subscription",
    question: "What is the Creative Club?",
    answer: "Creative Club is our monthly subscription at ₹299/month. Members get 1 free template per month, 50% off all physical products, early access to new features, exclusive monthly challenges, and priority support. Cancel anytime.",
  },
  {
    id: "12",
    category: "Subscription",
    question: "How do I cancel my subscription?",
    answer: "You can cancel anytime from your dashboard under Subscription Settings. Your benefits remain active until the end of your current billing period. No cancellation fees, ever.",
  },
  {
    id: "13",
    category: "Payments",
    question: "What payment methods do you accept?",
    answer: "We accept all major credit/debit cards, UPI (PhonePe, Google Pay, Paytm), net banking, EMI options, and international cards. All payments are secured by Stripe and Razorpay.",
  },
  {
    id: "14",
    category: "Payments",
    question: "Are my payment details secure?",
    answer: "100%. We never store your card details. All transactions are processed through PCI-DSS compliant payment gateways (Stripe for international, Razorpay for India). Your data is encrypted end-to-end.",
  },
  {
    id: "15",
    category: "Refunds",
    question: "What is your refund policy?",
    answer: "Digital downloads are non-refundable once accessed. Physical products can be returned within 7 days if damaged or defective — we'll replace or refund. Custom orders are non-refundable once production begins. See our full refund policy for details.",
  },
  {
    id: "16",
    category: "Business",
    question: "Do you offer bulk/corporate orders?",
    answer: "Yes! We love corporate orders. We offer special pricing for 10+ units, custom packaging with your logo, and dedicated account management. Contact us at corporate@canvasify.art for a custom quote.",
  },
  {
    id: "17",
    category: "Business",
    question: "Can Canvasify be used for schools?",
    answer: "Absolutely. We have special educational pricing and curriculum-aligned art kits for schools. Our education team can work with your institution to create customized programs. Contact education@canvasify.art.",
  },
  {
    id: "18",
    category: "Technical",
    question: "What file formats can I upload?",
    answer: "We accept JPG, PNG, HEIC, and WEBP files up to 25MB. For best results, use the original high-resolution photo directly from your phone or camera.",
  },
  {
    id: "19",
    category: "Technical",
    question: "Will my photos be kept private?",
    answer: "Your photos are stored securely on encrypted servers and are never shared, sold, or used to train AI models without your explicit consent. You can delete your photos and projects from your dashboard at any time.",
  },
  {
    id: "20",
    category: "Technical",
    question: "Can I download the same template multiple times?",
    answer: "Yes! Digital downloads are yours forever. You can download, reprint, and reuse your templates as many times as you want. There's no DRM or limit on personal use.",
  },
  {
    id: "21",
    category: "Experience",
    question: "I've never painted before — is this for me?",
    answer: "Absolutely! Paint-by-number is designed to be beginner-friendly. You don't need any artistic skill. The numbered system guides you step by step. Most customers finish their first painting within a week and are incredibly proud of the result.",
  },
  {
    id: "22",
    category: "Experience",
    question: "How long does a painting take to complete?",
    answer: "It depends on the size and complexity, but most people complete a 40x50cm painting in 10-20 hours spread over 1-2 weeks. Painting sessions are typically 30-60 minutes each — perfect for relaxing in the evenings.",
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  { id: "1", title: "Wedding by the Lake", category: "weddings", original_url: "/gallery/wedding-1-orig.jpg", transformed_url: "/gallery/wedding-1-pbn.jpg", author: "Priya & Arjun", likes: 234, featured: true },
  { id: "2", title: "Golden Retriever Max", category: "pets", original_url: "/gallery/pet-1-orig.jpg", transformed_url: "/gallery/pet-1-pbn.jpg", author: "Rahul M.", likes: 189, featured: true },
  { id: "3", title: "Santorini Sunset", category: "travel", original_url: "/gallery/travel-1-orig.jpg", transformed_url: "/gallery/travel-1-pbn.jpg", author: "Neha S.", likes: 312, featured: true },
  { id: "4", title: "Family Portrait 2024", category: "family", original_url: "/gallery/family-1-orig.jpg", transformed_url: "/gallery/family-1-pbn.jpg", author: "Sharma Family", likes: 156, featured: false },
  { id: "5", title: "Dream Home", category: "homes", original_url: "/gallery/home-1-orig.jpg", transformed_url: "/gallery/home-1-pbn.jpg", author: "Vikram D.", likes: 98, featured: false },
  { id: "6", title: "Mountain Valley", category: "nature", original_url: "/gallery/nature-1-orig.jpg", transformed_url: "/gallery/nature-1-pbn.jpg", author: "Kavitha R.", likes: 201, featured: true },
];

export const METRICS: Metric[] = [
  { label: "Templates Created", value: "10,000", suffix: "+", description: "And counting daily" },
  { label: "Happy Customers", value: "5,000", suffix: "+", description: "Across India & globe" },
  { label: "Satisfaction Rate", value: "98", suffix: "%", description: "Verified reviews" },
  { label: "Countries Shipped", value: "40", suffix: "+", description: "Global delivery" },
];

export const AI_STEPS = [
  {
    step: "01",
    title: "Image Segmentation",
    description: "Our AI uses semantic segmentation to identify and separate distinct regions — faces, backgrounds, objects — with pixel-perfect accuracy.",
    color: "#7C5CFF",
  },
  {
    step: "02",
    title: "Color Analysis",
    description: "Advanced color clustering algorithms analyze every pixel and reduce millions of colors to an optimized 12-36 color palette.",
    color: "#00E5FF",
  },
  {
    step: "03",
    title: "Number Assignment",
    description: "Each region is assigned a unique number corresponding to a specific paint color, creating clear, easy-to-follow painting zones.",
    color: "#B48EFF",
  },
  {
    step: "04",
    title: "Palette Generation",
    description: "A custom palette is generated with exact paint mixing instructions and color codes that match your original photo perfectly.",
    color: "#00D084",
  },
];

export const HOW_IT_WORKS = [
  {
    step: 1,
    title: "Upload Your Photo",
    description: "Choose any meaningful photo — wedding, pet, family, travel. Upload in seconds from your phone or computer.",
    icon: "Upload",
  },
  {
    step: 2,
    title: "AI Processing",
    description: "Our AI engine analyzes, segments, and transforms your photo into a perfect paint-by-number template in minutes.",
    icon: "Cpu",
  },
  {
    step: 3,
    title: "Customize & Preview",
    description: "Choose your palette size, preview the result, adjust cropping, and select your product format.",
    icon: "Sliders",
  },
  {
    step: 4,
    title: "Receive & Create",
    description: "Download instantly or receive your physical kit at home. Paint, frame, and cherish your personalized masterpiece forever.",
    icon: "Package",
  },
];

export const ROADMAP = [
  { quarter: "Q1 2025", title: "Paint By Number", status: "live", description: "Core product — launched and scaling." },
  { quarter: "Q2 2025", title: "Diamond Painting", status: "in_progress", description: "Transform photos into diamond painting templates with gem placement guides." },
  { quarter: "Q3 2025", title: "Personalized Puzzles", status: "planned", description: "Custom jigsaw puzzles from your photos in 250, 500, and 1000 pieces." },
  { quarter: "Q4 2025", title: "Creator Marketplace", status: "planned", description: "Artist marketplace where creators can sell custom templates globally." },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "1",
    slug: "how-paint-by-number-became-therapeutic",
    title: "How Paint-By-Number Became the Most Therapeutic Hobby of 2025",
    excerpt: "Scientists and psychologists are discovering what artists have known for decades — painting is meditative, stress-relieving, and deeply satisfying. Here's why personalized paint-by-number is leading the wellness art revolution.",
    content: "",
    cover_image: "/blog/therapeutic.jpg",
    author: { id: "1", name: "Aisha Kapoor", avatar: "AK", bio: "Art therapist and wellness writer", role: "Art & Wellness Editor" },
    category: "Wellness",
    tags: ["art therapy", "mindfulness", "painting", "wellness"],
    published_at: "2025-06-15",
    read_time: 6,
    featured: true,
  },
  {
    id: "2",
    slug: "perfect-photo-for-paint-by-number",
    title: "How to Choose the Perfect Photo for Your Paint-By-Number Kit",
    excerpt: "Not every photo makes a great painting. Our AI team shares the expert tips on choosing images that will result in stunning, detailed, and satisfying paint-by-number experiences.",
    content: "",
    cover_image: "/blog/perfect-photo.jpg",
    author: { id: "2", name: "Rohan Verma", avatar: "RV", bio: "Product designer and creative director", role: "Creative Director" },
    category: "Tips & Tricks",
    tags: ["tips", "photography", "getting started"],
    published_at: "2025-06-10",
    read_time: 5,
    featured: true,
  },
  {
    id: "3",
    slug: "wedding-anniversary-gift-ideas-2025",
    title: "10 Unique Wedding Anniversary Gift Ideas That Actually Last",
    excerpt: "Forget generic gifts. These thoughtful, personalized ideas will make your partner feel truly seen and loved — with personalized art topping the list.",
    content: "",
    cover_image: "/blog/anniversary.jpg",
    author: { id: "3", name: "Preethi Nair", avatar: "PN", bio: "Lifestyle and gift writer", role: "Lifestyle Editor" },
    category: "Gift Ideas",
    tags: ["gifts", "anniversary", "personalized", "wedding"],
    published_at: "2025-06-05",
    read_time: 7,
    featured: false,
  },
  {
    id: "4",
    slug: "ai-art-technology-explained",
    title: "How AI Turns Your Photos Into Art: The Technology Behind Canvasify",
    excerpt: "A deep dive into the computer vision, color theory, and machine learning that powers our image-to-art transformation engine.",
    content: "",
    cover_image: "/blog/ai-tech.jpg",
    author: { id: "4", name: "Aryan Mehta", avatar: "AM", bio: "ML engineer and tech writer", role: "Technology Editor" },
    category: "Technology",
    tags: ["AI", "technology", "computer vision", "machine learning"],
    published_at: "2025-05-28",
    read_time: 9,
    featured: false,
  },
  {
    id: "5",
    slug: "paint-by-number-tips-for-beginners",
    title: "15 Expert Tips for Beginners Starting Their First Paint-By-Number",
    excerpt: "Everything you need to know before you pick up a brush. From setting up your workspace to blending techniques that make your painting pop.",
    content: "",
    cover_image: "/blog/beginners.jpg",
    author: { id: "2", name: "Rohan Verma", avatar: "RV", bio: "Product designer and creative director", role: "Creative Director" },
    category: "Tips & Tricks",
    tags: ["beginners", "tips", "painting technique", "guide"],
    published_at: "2025-05-20",
    read_time: 8,
    featured: true,
  },
  {
    id: "6",
    slug: "corporate-gifting-with-personalized-art",
    title: "Why Personalized Art Is the Best Corporate Gift in 2025",
    excerpt: "Employee wellness, team building, and client appreciation — personalized art kits are revolutionizing how companies express gratitude and culture.",
    content: "",
    cover_image: "/blog/corporate.jpg",
    author: { id: "5", name: "Divya Shah", avatar: "DS", bio: "Business strategist and writer", role: "Business Editor" },
    category: "Business",
    tags: ["corporate", "gifts", "employee wellness", "team building"],
    published_at: "2025-05-15",
    read_time: 5,
    featured: false,
  },
];
